# Generated by Django 2.1.3 on 2018-12-01 20:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("base", "0004_patient_email")]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="url",
            field=models.FileField(blank=True, upload_to=base.models.get_scan_path),
        )
    ]
