# Generated by Django 2.1.4 on 2018-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("base", "0006_auto_20181201_2015")]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="scan_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="seg_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
