# Generated by Django 2.1.3 on 2018-12-01 18:27

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181201_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.FileField(blank=True, default='files/default.png', null=True, upload_to=base.models.get_file_path),
        ),
    ]
