# Generated by Django 2.1.3 on 2018-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181201_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='url',
            new_name='file',
        ),
    ]
