alpha: 3.0
batch_size: 2
cfg: unet_ce_hard
criterion: hard_cross_entropy
data_dir: /root/data/MICCAI_BraTS_2018_Data_Training/
dataset: SingleData
gpu: '0'
name: unet_ce_hard
net: Unet
net_params:
  dropout: 0.3
  n: 16
  norm: gn
num_epochs: 300
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
root: /root/data/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 2001
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: /root/data/MICCAI_BraTS_2018_Data_Validation/
test_transforms: Compose([ Pad((0, 0, 0, 5, 0)), NumpyType((np.float32, np.int64)),
  ])
train_dir: /root/code/BraTS/ckpts
train_list: all.txt
train_transforms: Compose([ RandCrop(128), NumpyType((np.float32, np.int64)), ])
valid_freq: 50
workers: 8
