# Generated by Django 2.1.3 on 2018-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181201_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='lol@lol.com', max_length=254),
            preserve_default=False,
        ),
    ]
