# Generated by Django 2.1.3 on 2018-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181201_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
